-- Generated by HyprMod

local vars = require("variables")

-- Chinese locale for the Hyprland session
hl.env("LANG", "zh_CN.UTF-8")
hl.env("LC_ALL", "zh_CN.UTF-8")

-- Fcitx5 input method
hl.env("QT_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("SDL_IM_MODULE", "fcitx")

-- Settings
hl.config({
    cursor = {
        hide_on_key_press = true,
        inactive_timeout = 3,
        no_warps = false,
    },
    general = {
        border_size = 2,
    },
    input = {
        accel_profile = "flat",
        kb_layout = "us",
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1440@165.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.global("caelestia:clipboard"))
hl.unbind("SUPER + ALT + E")
hl.bind("SUPER + ALT + E", hl.dsp.exec_cmd(vars.terminal .. " -e fish -ic yazi"))
hl.unbind("SUPER + O")
hl.bind("CTRL + SUPER + O", hl.dsp.exec_cmd("foot -e fish -ic codex"))
hl.unbind("SUPER + SHIFT + O")
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("/home/yukong/.local/bin/toggle-transparency"))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.global("caelestia:windowSwitcher"))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.global("caelestia:keybinds"))
hl.unbind("SUPER + ALT + W")
hl.bind("SUPER + ALT + W", hl.dsp.global("caelestia:wallpaper"))
hl.unbind("SUPER + TAB")
hl.bind("SUPER + TAB", hl.dsp.global("caelestia:workspaceOverview"))

-- Special workspaces
hl.unbind("ALT + TAB")
hl.bind("ALT + TAB", hl.dsp.layout("cyclenext"), { repeating = true })
hl.unbind("SHIFT + ALT + TAB")
hl.bind("SHIFT + ALT + TAB", hl.dsp.layout("cycleprev"), { repeating = true })
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("caelestia toggle steam"))
hl.bind("SUPER + O", hl.dsp.exec_cmd("caelestia toggle on_together"))
hl.bind("CTRL + SUPER + ALT + UP", hl.dsp.exec_cmd("caelestia shell hypr cycleSpecialWorkspace prev"))
hl.bind("CTRL + SUPER + ALT + DOWN", hl.dsp.exec_cmd("caelestia shell hypr cycleSpecialWorkspace next"))

-- ScrollOverview and the scrolling layout shortcuts from dotfile-noc.
local plugin_path = (os.getenv("HOME") or "/home/yukong") .. "/.local/src/hyprland-scroll-overview/scrolloverview.so"
hl.plugin.load(plugin_path)

local state_root = os.getenv("XDG_STATE_HOME") or ((os.getenv("HOME") or "/home/yukong") .. "/.local/state")
local layout_dir = state_root .. "/hyprland"
local layout_path = layout_dir .. "/layout"
local layout_file = io.open(layout_path, "r")
if layout_file then
    local saved_layout = layout_file:read("*l")
    layout_file:close()
    if saved_layout == "dwindle" or saved_layout == "scrolling" then
        hl.config({ general = { layout = saved_layout } })
    end
end

hl.config({ scrolling = { fullscreen_on_one_column = true, wrap_focus = false, wrap_swapcol = false } })

hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
hl.bind("SUPER + SHIFT + J", function()
    local workspace = hl.get_active_workspace()
    local current_layout = workspace and workspace.tiled_layout or hl.get_config("general.layout")
    local next_layout = current_layout == "scrolling" and "dwindle" or "scrolling"
    os.execute("mkdir -p " .. string.format("%q", layout_dir))
    local state = io.open(layout_path, "w")
    if state then
        state:write(next_layout .. "\n")
        state:close()
    end
    hl.config({ general = { layout = next_layout } })
end)

local function focus_or_wrap(direction, short_direction)
    return function()
        local workspace = hl.get_active_workspace()
        local win = hl.get_active_window()
        if workspace and workspace.tiled_layout == "scrolling" and win and not win.floating then
            hl.dispatch(hl.dsp.layout("focus " .. short_direction))
        else
            hl.dispatch(hl.dsp.focus({ direction = direction }))
        end
    end
end

for _, direction in ipairs({ "left", "right" }) do
    hl.unbind("SUPER + " .. direction)
    hl.bind("SUPER + " .. direction, focus_or_wrap(direction, direction:sub(1, 1)))
end

local function move_or_swap(direction, short_direction)
    return function()
        local workspace = hl.get_active_workspace()
        if workspace and workspace.tiled_layout == "scrolling" then
            hl.dispatch(hl.dsp.layout("swapcol " .. short_direction))
        else
            hl.dispatch(hl.dsp.window.move({ direction = direction }))
        end
    end
end

for _, direction in ipairs({ "left", "right" }) do
    hl.unbind("SUPER + SHIFT + " .. direction)
    hl.bind("SUPER + SHIFT + " .. direction, move_or_swap(direction, direction:sub(1, 1)))
end

local function scrolling_action(action)
    return function()
        local workspace = hl.get_active_workspace()
        if workspace and workspace.tiled_layout == "scrolling" then
            hl.dispatch(hl.dsp.layout(action))
        end
    end
end

hl.bind("CTRL + SUPER + UP", scrolling_action("consume"))
hl.bind("CTRL + SUPER + DOWN", scrolling_action("expel"))

local function resize_window(x_percent, y_percent)
    return function()
        local win = hl.get_active_window()
        if not win or not win.size then return end
        local workspace = hl.get_active_workspace()
        if workspace and workspace.tiled_layout == "scrolling" and not win.floating and x_percent ~= 0 then
            hl.dispatch(hl.dsp.layout(string.format("colresize %+.2f", x_percent / 100)))
        else
            hl.dispatch(hl.dsp.window.resize({
                x = win.size.x * x_percent / 100,
                y = win.size.y * y_percent / 100,
                relative = true,
            }))
        end
    end
end

for _, binding in ipairs({
    { "SUPER + minus", -10, 0 }, { "SUPER + equal", 10, 0 },
    { "SUPER + SHIFT + minus", 0, -10 }, { "SUPER + SHIFT + equal", 0, 10 },
    { "SUPER + ALT + left", -10, 0 }, { "SUPER + ALT + right", 10, 0 },
    { "SUPER + ALT + up", 0, -10 }, { "SUPER + ALT + down", 0, 10 },
}) do
    hl.unbind(binding[1])
    -- Caelestia defines these names with an initial capital letter.
    local capitalized = binding[1]:gsub("([%a]+)$", function(key)
        return key:sub(1, 1):upper() .. key:sub(2)
    end)
    hl.unbind(capitalized)
    hl.bind(binding[1], resize_window(binding[2], binding[3]), { repeating = true })
end

if hl.plugin and hl.plugin.scrolloverview then
    hl.config({ plugin = { scrolloverview = {
        gesture_distance = 300,
        scale = 0.5,
        workspace_gap = 100,
        layout = "vertical",
        wallpaper = 2,
        blur = true,
        shadow = { enabled = true, range = 30 },
    } } })
    hl.plugin.scrolloverview.gesture({ fingers = 3, direction = "vertical" })
end

hl.bind("SUPER + G", function()
    if hl.plugin and hl.plugin.scrolloverview then
        hl.plugin.scrolloverview.overview("toggle all")
    end
end)

hl.workspace_rule({ workspace = "special:special", layout = "scrolling" })
hl.workspace_rule({ workspace = "special:communication", layout = "monocle" })
hl.workspace_rule({ workspace = "special:music", layout = "monocle" })
hl.workspace_rule({ workspace = "special:sysmon", layout = "monocle" })

hl.window_rule({ match = { class = "^(Zoom)$" }, float = true, center = true })
hl.window_rule({ match = { class = "^Chat$" }, float = true })
hl.window_rule({
    match = { class = "^mpv$" },
    opaque = true,
    opacity = "1.0 override 1.0 override 1.0 override",
    float = true,
    size = { 1280, 720 },
    idle_inhibit = "focus",
})
hl.window_rule({
    match = { class = "^mpv$", float = true },
    dim_around = true,
    keep_aspect_ratio = true,
    stay_focused = true,
    center = true,
})
hl.window_rule({ match = { class = "^mpv$", float = false }, pseudo = true })
hl.window_rule({ match = { class = "^SVPManager$" }, workspace = "special:special silent" })
hl.window_rule({
    match = { class = "moe.tsuna.tsukimi" },
    opacity = "1.0 override 1.0 override 1.0 override",
    opaque = true,
})
hl.window_rule({ match = { class = "^(slack|com.rtosta.zapzap)$" }, workspace = "special:communication" })
hl.window_rule({ match = { class = "^wechat$" }, workspace = "special:communication silent" })
hl.window_rule({
    match = {
        class = "^(Thunar|thunar)$",
        workspace = "special:communication",
    },
    float = true,
    size = { 1200, 800 },
})
hl.window_rule({ match = { class = "Todoist|cohesion|obsidian" }, workspace = "special:todo" })
hl.window_rule({ match = { initial_title = "On-Together" }, workspace = "special:on_together" })

-- Wallpapers
hl.unbind("SUPER + F10")
hl.bind("SUPER + F10", hl.dsp.exec_cmd("caelestia wallpaper -r"))
hl.unbind("SUPER + SHIFT + F10")
hl.bind("SUPER + SHIFT + F10", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-anime-wallpaper-noctalia"))
hl.unbind("SUPER + F11")
hl.bind("SUPER + F11", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-konachan-nsfw-lite-wallpaper-caelestia"))
hl.unbind("SUPER + SHIFT + F11")
hl.bind("SUPER + SHIFT + F11", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-konachan-wallpaper-caelestia"))
hl.unbind("SUPER + F12")
hl.bind("SUPER + F12", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-yandere-sfw-wallpaper-caelestia"))
hl.unbind("SUPER + SHIFT + F12")
hl.bind("SUPER + SHIFT + F12", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-yandere-nsfw-wallpaper-caelestia"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("flclash")
end)

-- Dynamic cursor plugin
if hl.plugin.dynamic_cursors then
    hl.config({ plugin = { dynamic_cursors = {
        enabled = true,
        mode = "none",
    } } })

    hl.bind("SUPER + CTRL + Z", hl.plugin.dynamic_cursors.dsp_magnify({ duration = 2000, size = 4.0 }))
end
