-- Generated by HyprMod

local vars = require("variables")

-- Settings
hl.config({
    cursor = {
        hide_on_key_press = true,
        inactive_timeout = 3,
        no_warps = false,
    },
    general = {
        border_size = 2,
    },
    input = {
        accel_profile = "flat",
        kb_layout = "us",
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "2560x1440@165.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.global("caelestia:clipboard"))
hl.unbind("SUPER + ALT + E")
hl.bind("SUPER + ALT + E", hl.dsp.exec_cmd(vars.terminal .. " -e fish -ic yazi"))
hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.exec_cmd("foot -e fish -ic codex"))
hl.unbind("SUPER + SHIFT + O")
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("/home/yukong/.local/bin/toggle-transparency"))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.global("caelestia:windowSwitcher"))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.global("caelestia:keybinds"))
hl.unbind("SUPER + ALT + W")
hl.bind("SUPER + ALT + W", hl.dsp.global("caelestia:wallpaper"))
hl.unbind("SUPER + TAB")
hl.bind("SUPER + TAB", hl.dsp.global("caelestia:workspaceOverview"))

-- Wallpapers
hl.unbind("SUPER + F10")
hl.bind("SUPER + F10", hl.dsp.exec_cmd("caelestia wallpaper -r"))
hl.unbind("SUPER + SHIFT + F10")
hl.bind("SUPER + SHIFT + F10", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-anime-wallpaper-noctalia"))
hl.unbind("SUPER + F11")
hl.bind("SUPER + F11", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-konachan-nsfw-lite-wallpaper-caelestia"))
hl.unbind("SUPER + SHIFT + F11")
hl.bind("SUPER + SHIFT + F11", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-konachan-wallpaper-caelestia"))
hl.unbind("SUPER + F12")
hl.bind("SUPER + F12", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-yandere-sfw-wallpaper-caelestia"))
hl.unbind("SUPER + SHIFT + F12")
hl.bind("SUPER + SHIFT + F12", hl.dsp.exec_cmd("/home/yukong/.local/bin/random-yandere-nsfw-wallpaper-caelestia"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("flclash")
end)
